#!/bin/bash

# Creates executable file 'se1-ex3' from the source code
gcc -Wall -pedantic -std=c99 -g -o se1-ex3 se1-ex3.c se1-ex3-tests.c

# If created successfully, execute the program to get test results
if [ $? = 0 ]; then	./se1-ex3; fi
