#!/bin/bash

# Creates executable file 'se1-ex4' from the source code
gcc -Wall -pedantic -std=c99 -g -o se1-ex4 se1-ex4.c se1-ex4-tests.c

# If created successfully, execute the program to get test results
if [ $? = 0 ]; then	./se1-ex4; fi
