#!/bin/bash

# Creates executable file 'se2-ex3' from the source code
gcc -Wall -pedantic -std=c99 -g -o se2-ex3 se2-ex3.s se2-ex3-tests.c

# If created successfully, execute the program to get test results
if [ $? = 0 ]; then	./se2-ex3; fi
